<?php
// KJ Sencha benodigdheden
$this->extJs()->loadLibrary();

$this->kjSenchaVariables();
$this->kjSenchaLoaderConfig();
//$this->kjSenchaDirectApi();
// Einde KJ Sencha benodigdheden.

echo $this->headScript()->appendFile($this->basePath() . '/js/JaztecAdmin/App.js');

?>

<script type="text/javascript">
    
    var App = {};
    Ext.onReady(function () {
        App = Ext.create('JaztecAdmin.App');
    });

</script>