<?php echo $this->doctype(); ?>

<html lang="nl">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('Jaztec Administratie'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
  </head>
  <body>
      <?php echo $this->content; ?>
  </body>
</html>
