<?php echo $this->doctype(); ?>

<html lang="nl">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Jaztec Administratie'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
        
        <?php
            // KJ Sencha benodigdheden
            $this->extJs()->loadLibrary();

            $this->kjSenchaVariables();
            $this->kjSenchaLoaderConfig();
            $this->kjSenchaDirectApi();
            // Einde KJ Sencha benodigdheden.

        ?>
    </head>
    <body>
        <?php echo $this->content; ?>
        <?php echo $this->inlineScript()->appendFile($this->basePath() . '/js/JaztecAdmin/app.js'); ?>
    </body>
</html>
